web/flask_website/views/community.py
from flask import Blueprint, render_template, jsonify
from flask_website.utils import request_wants_json
from flask_website.listings.projects import projects

mod = Blueprint('community', __name__, url_prefix='/community')


@mod.route('/')
def index():
    return render_template('community/index.html')


@mod.route('/irc/')
def irc():
    return render_template('community/irc.html')


@mod.route('/badges/')
def badges():
    return render_template('community/badges.html')


@mod.route('/poweredby/')
def poweredby():
    if request_wants_json():
        return jsonify((k, [p.to_json() for p in v])
                       for k, v in projects.iteritems())
    return render_template('community/poweredby.html', projects=projects)


@mod.route('/logos/')
def logos():
    return render_template('community/logos.html')

web/flask_website/views/mailinglist.py
from __future__ import with_statement
from flask import Blueprint, render_template, redirect


mod = Blueprint('mailinglist', __name__, url_prefix='/mailinglist')


@mod.route('/')
def index():
    return render_template('mailinglist/index.html')


@mod.route('/archive/', defaults={'page': 1})
@mod.route('/archive/page/<int:page>/')
def archive(page):
    return redirect('http://librelist.com/browser/flask/')


@mod.route('/archive/<int:year>/<int:month>/<int:day>/<slug>/')
def show_thread(year, month, day, slug):
    return redirect('http://librelist.com/browser/flask/%s/%s/%s/%s'
                    % (year, month, day, slug))

web/flask_website/templates/community/badges.html
{% extends "community/layout.html" %}
{% block title %}Badges{% endblock %}
{% macro badge(filename, title) -%}
<a href="{{ url_for('general.index', _external=true) }}"><img
   src="{{ url_for('static', filename='badges/' ~ filename, _external=true) }}"
   border="0"
   alt="{{ title }}"
   title="{{ title }}"></a>
{%- endmacro %}
{% macro show_badge(filename, title) -%}
  <div class=badge>
    <p>{{ badge(filename, title) }}
    <pre>{{ badge(filename, title)|forceescape }}</pre>
  </div>
{%- endmacro %}
{% block body %}
  <h2>Badges</h2>
  <p>
    If you want to share the word and want to add a “powered by
    Flask” badge to your website you can display one of these
    nifty badges.  We also have some badges if your website is not
    yet powered by Flask :)
  <h3>Large Badges</h3>
  {{ show_badge('flask-powered.png', 'Flask powered') }}
  {{ show_badge('i-wish.png', 'I wish this site were Flask powered') }}
  {{ show_badge('unfortunately-not.png', 'Unfortunately not Flask powered') }}
  <h3>Small Badges</h3>
  {{ show_badge('flask-project-s.png', 'a Flask project') }}
  {{ show_badge('made-with-flask-s.png', 'made with Flask') }}
  {{ show_badge('powered-by-flask-s.png', 'powered by Flask') }}
  <p><small>Idea for badges inspired by the Django Framework badges.</small></p>
{% endblock %}

web/flask_website/templates/community/index.html
{% extends "community/layout.html" %}
{% block body %}
    <p>
        Flask is supported by an active, helpful community.
        Get involved by joining the
        <a href="{{ url_for('mailinglist.index') }}">mailing list</a> and
        <a href="{{ url_for('community.irc') }}">IRC channel</a>.
        Discussion for developers using Flask as well as working on the core is welcome.
    <p>
        If you want to spread the word, there is also a selection of
        <a href="{{ url_for('community.badges') }}">badges</a> and
        <a href="{{ url_for('community.logos') }}">logos</a>
        you can use on your own website.
        There are also shirts and mugs available at the
        <a href="http://flask.spreadshirt.net/">Flask store</a>, and
        <a href="https://www.stickermule.com/marketplace/6037-flask-web-framework">stickers</a> too.
    <ul>
        <li><a href=http://github.com/pallets/flask/issues>Issues Tracker</a> - for bugs and feature requests
        <li><a href="{{ url_for('mailinglist.index') }}">Mailing List</a> - for help and long term discussion
        <li><a href="{{ url_for('community.irc') }}">IRC Channel</a> - for general help and discussion
        <li><a href="http://stackoverflow.com/questions/tagged/flask">Stack Overflow</a> - for <a href="http://stackoverflow.com/help/asking">focused questions</a> about code
        <li><a href="{{ url_for('community.poweredby') }}">Powered By Flask</a>
        <li><a href="{{ url_for('community.badges') }}">Badges</a>
        <li><a href="{{ url_for('community.logos') }}">Logos</a>
        <li><a href="http://flask.spreadshirt.net/">Store</a>
        <li><a href="https://www.stickermule.com/marketplace/6037-flask-web-framework">Stickers</a></li>
    </ul>
{% endblock %}

web/flask_website/templates/community/irc.html
{% extends "community/layout.html" %}
{% block title %}IRC Channel{% endblock %}
{% block body %}
  <h2>IRC Channel</h2>
  <p>
    The Flask IRC channel is <code>#pocoo</code> on irc.freenode.net.
    Flask shares that channel with other Pocoo projects, so please
    let the others know that you are talking about Flask when asking
    a question.
  <p>
    You can use any IRC client to connect to freenode.  If you don't
    have one yet, pick one from the list:
  <ul>
    <li><a href="http://pidgin.im/">Pidgin</a>, Windows, Linux, OS X
    <li><a href="http://xchat.org/">X-Chat</a>, Linux
    <li><a href="http://mirc.com/">mirc</a>, Windows
    <li><a href="http://colloquy.info/">colloquy</a>, OS X
  </ul>
  <p>
    Alternatively you can also use the freenode web interface to
    join the IRC channel: <a href="http://bit.ly/pocooirc">open
    #pocoo in your browser</a>.
  <p>
    If you want to read up on older discussions you can access
    the IRC logs on <a href=https://botbot.me/freenode/pocoo/>https://botbot.me/freenode/pocoo/</a>.
{% endblock %}

web/flask_website/templates/community/layout.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { background-image: url({{ url_for('static', filename='community.png') }}); }
  </style>
{% endblock %}
{% block body_title %}
  <h1><span>Flask Community</span></h1>
{% endblock %}

web/flask_website/templates/community/logos.html
{% extends "community/layout.html" %}
{% block title %}Logos{% endblock %}
{% macro logo(format) -%}
  <a href="{{ url_for('static', filename='logo/flask.' ~ format)
    }}">{{ format|upper }} format</a>
{%- endmacro %}
{% block body %}
  <h2>Logos</h2>
  <p>
    The Flask logo is available for download and use in the formats
    below.  You can use the logo to promote Flask like you want.
    The image is licensed under the “Flask Artwork License”.
    <a href="{{ url_for('docs.show', page='license')
      }}#flask-artwork-license">Read license text</a>.
  <ul>
    <li>{{ logo('png') }}: for online and screen usage
    <li>{{ logo('svg') }}: for online and screen usage
    <li>{{ logo('eps') }}: for print use
    <li>{{ logo('pdf') }}: for print use
  </ul>
  <p>
    The font used in the logo is “Hightower Text roman” from the
    Font Bureau foundry.  The font can be purchased from
    <a href="http://www.ascenderfonts.com/font/hightower-text-roman.aspx"
    >Ascender Fonts</a>.
{% endblock %}

web/flask_website/templates/community/poweredby.html
{% extends "community/layout.html" %}
{% block title %}Powered By Flask{% endblock %}
{% macro project_url(project) %}
{%- if project.url -%}
  {{ project.url }}
 {%- elif project.source -%}
  {{ project.source }}
{%- endif -%}
{% endmacro %}
{% macro render_projects(kind) %}
  {% for project in projects[kind] %}
  <div class=project>
    <h4><a href="{{ project_url(project) }}">{{ project.name }}</a></h4>
    <div class=description>
      {{ project.description }}
    </div>
    <dl>
      {% if project.url %}
      <dt>URL:
      <dd><a href="{{ project.url }}">{{ project.host }}</a>
      {% endif %}
      {% if project.source %}
      <dt>Sourcecode:
      <dd><a href="{{ project.source }}">{{ project.sourcehost }}</a>
      {% endif %}
    </dl>
  </div>
  {% endfor %}
{% endmacro %}
{% block body %}
  <h2>Powered By Flask</h2>
  <p>
    This is a list of websites and projects that disclosed that they
    are running on Flask.  If you want your own website or project
    listed here,
    <a href=mailto:armin.ronacher@active-4.com>send me a mail</a>
    with the URL, name and description of the website.
  <h3>Websites</h3>
  {{ render_projects('websites') }}
  <h3>Applications</h3>
  {{ render_projects('apps') }}
{% endblock %}