web/flask_website/views/community.py
from flask import Blueprint, render_template, jsonify
from flask_website.utils import request_wants_json
from flask_website.listings.projects import projects

mod = Blueprint('community', __name__, url_prefix='/community')


@mod.route('/')
def index():
    return render_template('community/index.html')


@mod.route('/irc/')
def irc():
    return render_template('community/irc.html')


@mod.route('/badges/')
def badges():
    return render_template('community/badges.html')


@mod.route('/poweredby/')
def poweredby():
    if request_wants_json():
        return jsonify((k, [p.to_json() for p in v])
                       for k, v in projects.iteritems())
    return render_template('community/poweredby.html', projects=projects)


@mod.route('/logos/')
def logos():
    return render_template('community/logos.html')

web/flask_website/views/general.py
from flask import Blueprint, render_template, session, redirect, url_for, \
     request, flash, g, jsonify, abort
from flask_openid import COMMON_PROVIDERS
from flask_website import oid
from flask_website.search import search as perform_search
from flask_website.utils import requires_login, request_wants_json
from flask_website.database import db_session, User
from flask_website.listings.releases import releases

mod = Blueprint('general', __name__)


@mod.route('/')
def index():
    if request_wants_json():
        return jsonify(releases=[r.to_json() for r in releases])

    return render_template(
        'general/index.html',
        latest_release=releases[-1],
        # pdf link does not redirect, needs version
        # docs version only includes major.minor
        docs_pdf_version='.'.join(releases[-1].version.split('.', 2)[:2])
    )


@mod.route('/search/')
def search():
    q = request.args.get('q') or ''
    page = request.args.get('page', type=int) or 1
    results = None
    if q:
        results = perform_search(q, page=page)
        if results is None:
            abort(404)
    return render_template('general/search.html', results=results, q=q)


@mod.route('/logout/')
def logout():
    if 'openid' in session:
        flash(u'Logged out')
        del session['openid']
    return redirect(request.referrer or url_for('general.index'))


@mod.route('/login/', methods=['GET', 'POST'])
@oid.loginhandler
def login():
    if g.user is not None:
        return redirect(url_for('general.index'))
    if 'cancel' in request.form:
        flash(u'Cancelled. The OpenID was not changed.')
        return redirect(oid.get_next_url())
    openid = request.values.get('openid')
    if not openid:
        openid = COMMON_PROVIDERS.get(request.args.get('provider'))
    if openid:
        return oid.try_login(openid, ask_for=['fullname', 'nickname'])
    error = oid.fetch_error()
    if error:
        flash(u'Error: ' + error)
    return render_template('general/login.html', next=oid.get_next_url())


@mod.route('/first-login/', methods=['GET', 'POST'])
def first_login():
    if g.user is not None or 'openid' not in session:
        return redirect(url_for('.login'))
    if request.method == 'POST':
        if 'cancel' in request.form:
            del session['openid']
            flash(u'Login was aborted')
            return redirect(url_for('general.login'))
        db_session.add(User(request.form['name'], session['openid']))
        db_session.commit()
        flash(u'Successfully created profile and logged in')
        return redirect(oid.get_next_url())
    return render_template('general/first_login.html',
                           next=oid.get_next_url(),
                           openid=session['openid'])


@mod.route('/profile/', methods=['GET', 'POST'])
@requires_login
def profile():
    name = g.user.name
    if request.method == 'POST':
        name = request.form['name'].strip()
        if not name:
            flash(u'Error: a name is required')
        else:
            g.user.name = name
            db_session.commit()
            flash(u'User profile updated')
            return redirect(url_for('.index'))
    return render_template('general/profile.html', name=name)


@mod.route('/profile/change-openid/', methods=['GET', 'POST'])
@requires_login
@oid.loginhandler
def change_openid():
    if request.method == 'POST':
        if 'cancel' in request.form:
            flash(u'Cancelled. The OpenID was not changed.')
            return redirect(oid.get_next_url())
    openid = request.values.get('openid')
    if not openid:
        openid = COMMON_PROVIDERS.get(request.args.get('provider'))
    if openid:
        return oid.try_login(openid)
    error = oid.fetch_error()
    if error:
        flash(u'Error: ' + error)
    return render_template('general/change_openid.html',
                           next=oid.get_next_url())


@oid.after_login
def create_or_login(resp):
    session['openid'] = resp.identity_url
    user = g.user or User.query.filter_by(openid=resp.identity_url).first()
    if user is None:
        return redirect(url_for('.first_login', next=oid.get_next_url(),
                                name=resp.fullname or resp.nickname))
    if user.openid != resp.identity_url:
        user.openid = resp.identity_url
        db_session.commit()
        flash(u'OpenID identity changed')
    else:
        flash(u'Successfully signed in')
    return redirect(oid.get_next_url())

web/flask_website/views/mailinglist.py
from __future__ import with_statement
from flask import Blueprint, render_template, redirect


mod = Blueprint('mailinglist', __name__, url_prefix='/mailinglist')


@mod.route('/')
def index():
    return render_template('mailinglist/index.html')


@mod.route('/archive/', defaults={'page': 1})
@mod.route('/archive/page/<int:page>/')
def archive(page):
    return redirect('http://librelist.com/browser/flask/')


@mod.route('/archive/<int:year>/<int:month>/<int:day>/<slug>/')
def show_thread(year, month, day, slug):
    return redirect('http://librelist.com/browser/flask/%s/%s/%s/%s'
                    % (year, month, day, slug))

web/flask_website/templates/general/change_openid.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { background-image: url({{ url_for('static', filename='profile.png') }}); }
  </style>
{% endblock %}
{% block title %}Change OpenID{% endblock %}
{% block body %}
  <h2>Change OpenID</h2>
  <form action="" method=post>
    <p>
      You can the OpenID used to log into this website.  Right
      now your OpenID identity is
      <a href="{{ g.user.openid }}">{{ g.user.openid|displayopenid }}</a>
    <p>
      OpenID URL:
      <input type=text name=openid class=openid size=26>
      <input type=hidden name=next value="{{ next }}">
      <input type=submit value=Change>
      <input type=submit name=cancel value=Cancel>
    <p>
      Alternatively you can directly link your profile with one
      of the common id providers:
    <ul>
      <li><a href=?provider=aol>AOL</a>
      <li><a href=?provider=google>Google</a>
      <li><a href=?provider=yahoo>Yahoo</a>
    </ul>
  </form>
{% endblock %}

web/flask_website/templates/general/first_login.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { background-image: url({{ url_for('static', filename='login.png') }}); }
  </style>
{% endblock %}
{% block title %}First Login{% endblock %}
{% block body %}
  <h2>This is your First Login</h2>
  <form action="{{ url_for('general.first_login') }}" method=post>
    <p>
      This is your first login on this website.  You are about to sign
      in with the following OpenID: <a href="{{ openid }}">{{
        openid|displayopenid }}</a>
    <p>
      Before you can use this site we need a name for you.  This is what
      will be displayed next to all of your public contributions to this
      site.  Choose wisely because you cannot change this value later:
    <dl>
      <dt>Name:
      <dd><input type=text name=name value="{{ request.values.name }}" size=30>
    </dl>
    <p>
      <input type=hidden name=next value="{{ next }}">
      <input type=submit value=Continue>
      <input type=submit name=cancel value=Cancel>
  </form>
{% endblock %}

web/flask_website/templates/general/index.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { margin: 0 0 30px 0; background: url({{ url_for('static', filename='logo.png') }}) no-repeat center; height: 165px; }
    h1 span, p.tagline { display: none; }
  </style>
  <script type=text/javascript>
    $(function() {
      $('h1').bind('mousedown contextmenu', function(event) {
        if (event.button != 2)
          return;
        var box = $('div.logohint');
        if (!box.is(':visible'))
          box.animate({'height': 'show', 'opacity': 'show'}, 100);
        event.preventDefault();
        event.returnValue = false;
        return false;
      });
    });
  </script>
{% endblock %}
{% block body_title %}
  {{ super() }}
  <p class=tagline>because sometimes a pocket knife is not enough
  <div class=logohint style="display: none">
    <p>
      Are you interested in the logo?  We have it available in large versions so
      please if you use it head over to the <a href="{{ url_for('community.logos') }}">logo
      page</a> for the logo and the usage guidelines.
    <p>
      Quicklinks: <a href="{{ url_for('static', filename='logo/flask.png') }}">PNG</a>
      and <a href="{{ url_for('static', filename='logo/flask.eps') }}">EPS</a>
  </div>
{% endblock %}
{% block body %}
  <blockquote>
    Flask is a microframework for Python based on Werkzeug, Jinja 2 and good intentions.
    And before you ask: It's <a href="{{ url_for('docs.show', page='license')
      }}">BSD licensed</a>!
  </blockquote>
  <p class=latestver>
    <strong>Latest Version:</strong>
    <a href="{{ latest_release.detail_url }}">{{ latest_release.version }}</a>
  <h2>Flask is Fun</h2>
  <pre><span class=ig>from flask import Flask
app = Flask(__name__)</span>

@app.route("/")
def hello():
    return "Hello World!"
</pre>
  <h2>And Easy to Setup</h2>
  <pre><span class=ig>$ </span>pip install Flask
<span class=ig>$ </span>FLASK_APP=hello.py flask run
<span class=ig> * Running on http://localhost:5000/</span></pre>
  <iframe src="http://ghbtns.com/github-btn.html?user=pallets&amp;repo=flask&amp;type=watch&amp;count=true&amp;size=large" width="190" height="35" style="float: right;border: none"></iframe>
  <h2>Interested?</h2>
  <ul>
    <li><a href="{{ latest_release.detail_url }}">Download latest release</a> ({{ latest_release.version }})
    <li><a href="{{ url_for('docs.index') }}">Read the documentation</a>
    <li><a href="{{ url_for('mailinglist.index') }}">Join the mailinglist</a>
    <li><a href=https://github.com/pallets/flask>Fork it on github</a>
    <li><a href=https://github.com/pallets/flask/issues>Add issues and feature requests</a>
  </ul>
  <h2>What’s in the Box?</h2>
  <ul>
    <li>built-in development server and <a href="{{ url_for('docs.show',
      page='quickstart') }}#debug-mode">debugger</a>
    <li>integrated <a href="{{ url_for('docs.show',
      page='testing') }}">unit testing support</a>
    <li>RESTful <a href="{{ url_for('docs.show', page='quickstart')
      }}#routing">request dispatching</a>
    <li>uses <a href=http://jinja.pocoo.org/docs/>Jinja2 templating</a>
    <li>support for <a href="{{ url_for('docs.show', page='quickstart')
      }}#sessions">secure cookies</a> (client side sessions)
    <li>100% <a href=http://www.python.org/dev/peps/pep-0333/>WSGI 1.0</a> compliant
    <li>Unicode based
    <li>extensively <a href="{{ url_for('docs.index') }}">documented</a>
  </ul>
  <h2>What do Flask Apps look like?</h2>
  <p>
    If you are looking for some example code of applications written with Flask,
    have a look at the sources of the examples on github:
  <ul>
    <li><a href=https://github.com/pallets/flask/tree/master/examples/tutorial/>flaskr</a>
      — a microblog
    <li><a href=https://github.com/pallets/flask-website>this website</a>
      — static pages + mailinglist archives
  </ul>
  <h2>Contribute</h2>
  <p>Found a bug? Have a good idea for improving Flask? Head over to
    <a href=https://github.com/pallets/flask>Flask's github</a> page and
    create a new ticket or fork.  If you just want to chat with fellow
    developers, visit <a href="{{ url_for('community.irc') }}">the IRC
    channel</a> or join <a href="{{ url_for('mailinglist.index') }}"
    >the mailinglist</a>.  You can also directly add issues and feature
    requests to the <a href="https://github.com/pallets/flask/issues">
    issue tracker</a>.

<a href="https://github.com/pallets/flask"><img style="position: fixed; top: 0; right: 0; border: 0;"
  src="http://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png" alt="Fork me on GitHub"></a>
{% endblock %}

web/flask_website/templates/general/login.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { background-image: url({{ url_for('static', filename='login.png') }}); }
  </style>
{% endblock %}
{% block title %}Login{% endblock %}
{% block body %}
  <form action="" method=post>
    <p>
      For some of the features on this site (such as creating snippets
      or adding comments) you have to be signed in.  You don't need to
      create an account on this website, just sign in with an existing
      <a href=http://openid.net/>OpenID</a> account.
    <p>
      OpenID URL:
      <input type=text name=openid class=openid size=30>
      <input type=hidden name=next value="{{ next }}">
      <input type=submit value=Login>
    <p>
      Alternatively you can directly sign in by clicking on one of
      the providers here in case you don't know the identity URL:
    <ul>
      <li><a href=?provider=aol>AOL</a>
      <li><a href=?provider=google>Google</a>
      <li><a href=?provider=yahoo>Yahoo</a>
    </ul>
  </form>
{% endblock %}

web/flask_website/templates/general/profile.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { background-image: url({{ url_for('static', filename='profile.png') }}); }
  </style>
{% endblock %}
{% block title %}Profile{% endblock %}
{% block body %}
  <form action="" method=post>
    <p>
      Here you can change the profile information used for this
      website.  Please keep in mind that you can only have one
      OpenID identity linked to this account, if you change it
      the old one will no longer be able to sign in.
    <dl class=formlist>
      <dt>Name:
      <dd><input type=text name=name value="{{ name }}" size=30>
      <dt>OpenID:
      <dd>
        <span class=disabled>{{ g.user.openid|displayopenid }}</span>
        (<a href="{{ url_for('.change_openid') }}">change</a>)
    </dl>
    <p>
      <input type=submit value="Update profile">
  </form>
{% endblock %}

web/flask_website/templates/general/search.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { background-image: url({{ url_for('static', filename='search.png') }}); }
  </style>
{% endblock %}
{% block title %}Search{% endblock %}
{% block body %}
  <form action="" method=get class=search-box>
    <p>Search this website for:
      <input type=text name=q size=30 value="{{ q }}">
      <input type=submit value="Search">
  </form>
  {% if q %}
    <h2>Results for “{{ q }}”</h2>
    <ul class=search-results>
    {%- for result in results %}
      <li class="search-result-{{ result.kind }}">
        <p class=title><a href="{{ result.url }}">{{ result.title }}</a>
          <span class=kind>[{{ result.kind }}]</span>
        {%- if result.description %}
        <p class=description>{{ result.description }}
        {%- endif %}
    {%- else %}
      <li><em>We did not find anything :-(</em>
    {%- endfor %}
    </ul>
    <div class=pagination>
      {% if results.page > 1 %}
        <a href="{{ url_for('.search', q=q, page=results.page - 1) }}">&laquo; Previous</a>
      {% else %}
        <span class=disabled>&laquo; Previous</span>
      {% endif %}
      | <strong>{{ results.page }}</strong> |
      {% if results.page < results.pages %}
        <a href="{{ url_for('.search', q=q, page=results.page + 1) }}">Next &raquo;</a>
      {% else %}
        <span class=disabled>Next &raquo;</span>
      {% endif %}
    </div>
  {% endif %}
{% endblock %}