web/flask_website/views/mailinglist.py
from __future__ import with_statement
from flask import Blueprint, render_template, redirect


mod = Blueprint('mailinglist', __name__, url_prefix='/mailinglist')


@mod.route('/')
def index():
    return render_template('mailinglist/index.html')


@mod.route('/archive/', defaults={'page': 1})
@mod.route('/archive/page/<int:page>/')
def archive(page):
    return redirect('http://librelist.com/browser/flask/')


@mod.route('/archive/<int:year>/<int:month>/<int:day>/<slug>/')
def show_thread(year, month, day, slug):
    return redirect('http://librelist.com/browser/flask/%s/%s/%s/%s'
                    % (year, month, day, slug))

web/flask_website/templates/mailinglist/archive.html
{% extends "mailinglist/layout.html" %}
{% block title %}Mailinglist Archive{% endblock %}
{% block body %}
  <p class=backnav>
    <a href="{{ url_for('.index') }}">&laquo; list information</a>
  <h2>Mailinglist Archive</h2>
  <ul class=archive>
  {% for thread in threads %}
    <li><a href="{{ thread.url }}">{{ thread.title }}</a>
      <span class=meta>
        by {{ thread.author_name or thread.author_email }}
        on {{ thread.date|datetimeformat }}
        ({{ thread.reply_count }} repl{{ thread.reply_count == 1 and 'y' or 'ies' }})</span>
  {% endfor %}
  </ul>
  <div class=pagination>
    {% if page > 1 %}
      <a href="{{ url_for('mailinglist.archive', page=page - 1) }}">&laquo; Previous</a>
    {% else %}
      <span class=disabled>&laquo; Previous</span>
    {% endif %}
    | <strong>{{ page }}</strong> |
    {% if page < page_count %}
      <a href="{{ url_for('mailinglist.archive', page=page + 1) }}">Next &raquo;</a>
    {% else %}
      <span class=disabled>Next &raquo;</span>
    {% endif %}
  </div>
{% endblock %}

web/flask_website/templates/mailinglist/index.html
{% extends "mailinglist/layout.html" %}
{% block title %}Mailinglist{% endblock %}
{% block body %}
  <h2>Mailinglist Information</h2>
  <p>
    There is a mailinglist for Flask hosted on <a
    href="https://mail.python.org/mailman/listinfo/flask/">python.org</a> that
    you can use for both user requests and development discussions that may not
    fit well in a Github issue or StackOverflow question.

  <p>
    You can subscribe or change your subscription options at
    <a href="https://mail.python.org/mailman/listinfo/flask/">
    https://mail.python.org/mailman/listinfo/flask/</a>. If you're having
    problems, don't forget to check your Spam folder.

  <p>
    You can view the list archives at <a
    href="http://mail.python.org/pipermail/flask/">
    http://mail.python.org/pipermail/flask/</a>.

  <p>
    Before July 2015, we used librelist for the mailing list. You can view those
    archives here: <a href="{{ url_for('mailinglist.archive') }}">
    {{ url_for('mailinglist.archive') }}</a>. Just keep in mind any new messages
    should now be posted to <a
    href="https://mail.python.org/mailman/listinfo/flask/">the python.org
    Flask mailing list</a> mentioned above.

{% endblock %}

web/flask_website/templates/mailinglist/layout.html
{% extends "layout.html" %}
{% block head %}
  {{ super() }}
  <style type=text/css>
    h1 { background-image: url({{ url_for('static', filename='mailinglist.png') }}); }
  </style>
{% endblock %}
{% block body_title %}
  <h1><span>Flask Mailinglist</span></h1>
{% endblock %}

web/flask_website/templates/mailinglist/show_thread.html
{% extends "mailinglist/layout.html" %}
{% block title %}{{ thread.title }}{% endblock %}
{% block head %}
  {{ super() }}
  <script type=text/javascript src="{{ url_for('static',
    filename='mailinglist.js') }}"></script>
{% endblock %}
{% block body %}
  <p class=backnav>
    <a href="{{ url_for('.archive') }}">&laquo; back to archive</a>
  <h2>{{ thread.title }}</h2>

  <ul class=mailtree>
  {% for mail in [thread.root] recursive %}
    <li><div class=link id="link-{{ mail.id }}"><a href="#{{
      mail.id }}">{{ mail.subject }}</a> by {{
      mail.author_name or mail.author_email }}</div>
    {% if mail.children %}<ul>{{ loop(mail.children) }}</ul>{% endif %}
  {% endfor %}
  </ul>

  {% for mail in [thread.root] recursive %}
    <div class=mail id="{{ mail.id }}">
      <h3>{{ mail.subject }}</h3>
      <dl>
        <dt>From:
        <dd class=from>{{ mail.author_name or mail.author_email }}
        <dt>Date:
        <dd>{{ mail.date|datetimeformat }}
      </dl>
      <pre>{{ mail.rendered_text() }}</pre>
      {% if mail.children %}
        <div class=children>{{ loop(mail.children) }}</div>
      {% endif %}
    </div>
  {% endfor %}
{% endblock %}